spring:
  application:
    name: ProjectOne
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: changemeinprod!
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always

server:
  port: 5000
